cabal-version:   3.0
name:            jizhang
version:         0.1.0.0
synopsis:        Web application for group expense management
description:
  Jizhang is a web application designed to help groups manage their expenses.

license:         MIT
license-file:    LICENSE
author:          Potato Hatsue
maintainer:      1793913507@qq.com
copyright:       2025 Potato Hatsue
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

executable jizhang
  import:           warnings
  main-is:          Main.hs
  other-modules:
    Jizhang.API
    Jizhang.API.Group
    Jizhang.API.Import
    Jizhang.API.Record
    Jizhang.API.Report
    Jizhang.API.Types
    Jizhang.API.User
    Jizhang.API.Utils
    Jizhang.Common.MyUUID
    Jizhang.Database
    Jizhang.Database.Schema

  build-depends:
    , aeson
    , base
    , beam-core          ^>=0.10.4
    , beam-sqlite        ^>=0.5.4
    , bytestring
    , cassava
    , containers
    , http-media
    , log-base           ^>=0.12.1
    , monad-control
    , mtl
    , servant
    , servant-server
    , servant-swagger
    , sqlite-simple
    , swagger2
    , text
    , time
    , transformers
    , transformers-base
    , uuid
    , wai
    , wai-log
    , warp

  hs-source-dirs:   app
  default-language: Haskell2010
